export default
[
  { element: 'acreage', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'inPoolAcreage', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'bufferAcreage', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'nsdAcreage', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'contractType', showOnlyIfFormSubmitted: true, showOnlyIfNoOverride: false },
  { element: 'contractSubType', showOnlyIfFormSubmitted: true, showOnlyIfNoOverride: false },
  { element: 'tractNumber', showOnlyIfFormSubmitted: true, showOnlyIfNoOverride: true },
  { element: 'sequence', showOnlyIfFormSubmitted: true, showOnlyIfNoOverride: true },
  { element: 'districtid', showOnlyIfFormSubmitted: true, showOnlyIfNoOverride: true },
  { element: 'terminationReason', showOnlyIfFormSubmitted: true, showOnlyIfNoOverride: false },
  { element: 'altIdInformation', showOnlyIfFormSubmitted: true, showOnlyIfNoOverride: false },
  { element: 'minimumRoyalty', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'royaltyPercent', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'mimimumRoyaltySalesPrice', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'firstYearRentalBonusAmount', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'totalBonusAmount', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'leaseExtensionBonus', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'secondThroughFourthYearDelayRental', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'secondThroughFourthYearShutInRate', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'fifthYearOnwardDelayRental', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'fifthYearOnwardShutinRate', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'storageFee', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'allowableVariancePerAuditFieldPercent', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'producerPriceIndex', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'testOfWellEconomy', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'performanceSurety', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'agreementFee', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'storageWellPayment', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'storageBaseRentalPayment', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'storageRentalPayment', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
  { element: 'contractRentalPayment', showOnlyIfFormSubmitted: false, showOnlyIfNoOverride: false },
];
