import * as constants from '../../constants';

export default function initState() {
  return {
    well: {
      wellId: 0,
      apiNum: null,
      spudDate: null,
      initialProductionDate: null,
      bofAppDate: null,
      plugDate: null,
      shutInDate: null,
      completionDate: null,
      autoUpdatedAllowedInd: true,
    },
    contractId: 0,
    unitId: 0,
    paymentId: 0,
    suretyId: 0,
    editmode: true,
    tracts: [],
    pads: [],
    submitInd: false,
    apiStates: [],
    apiCounties: [],
    wellStatuses: [],
    wellTypes: [],
    lessees: [],
    contracts: [],
    townships: [],
    districtTractJunctions: [],
    districts: [],
    producingFormations: [],
    deepestFormations: [],
    wellTractInfos: [],
    historicalInfos: [],
    wellTractInfosExistInd: false,
    contractEventDetailReasonsForChange: [],
    contractEventDetailReasonsForChangeId: null,
    apiStateCode: constants.ApiStateCode_Pennsylvania,
    apiCountyCode: 0,
    apiUniqueIdentifier: null,
    directionalSideTrackCode: '00',
    eventSequenceCode: '00',
    alternateIdDropDownLabel: constants.AlternateIdDropDownLabel_NA,
    wellLogTestTypes: [],
    digitalLogs: [],
    digitalImageLogs: [],
    hardCopyLogs: [],
    units: [],
    wellboreLengthInd: false,
    wellboreShares: [],
    sureties: [],
  };
}
